### ISSUE TITLE
Unable to install @kafkajs/zstd

### ISSUE THREAD

**Issue by manashpracticearea** [kafkajs/zstd#6]
Unable to install @kafkajs/zstd v0.1.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cppzst@2.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cppzst@2.0.6 install script.

Also , cppzst library has dependency on segfault-handler.

Tried to install cppzst and segfault-handler separately but still experiencing issues.

**Comment by manashpracticearea** [comment]
@Nevon , could you please assist . I am unable to install kafkajs/zstd . It has dependency on segfault-handler and failing to install segfault-handler

**Comment by Nevon** [comment]
See the note at the top of the readme:

> NOTE: This codec relies on [cppzst](https://www.npmjs.com/package/cppzst) for compression and decompression. Please divert any issues with cppzst there, and only open issues on this repo in case the version being used here needs to be updated.
> 
> This package is provided on a best-effort basis. See https://github.com/kafkajs/zstd/issues/2
